os: osx
osx_image: xcode11.2
language: objective-c
cache: cocoapods
xcode_project: sdk-core-swift.xcodeproj 
xcode_scheme: sdk-core-swift
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

before_install:
  - gem install cocoapods --pr
  - pod repo update

install:
  - gem install slather
  - gem install xcpretty

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-darwin-amd64 > ./cc-test-reporter &&
    chmod 777 ./cc-test-reporter &&
    ./cc-test-reporter before-build 

script:
  - pod deintegrate
  - pod install
  - xcodebuild -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination platform\=iOS\ Simulator,OS\=13.2,name\=iPhone\ 11 build test clean -UseModernBuildSystem=NO | xcpretty

after_script:
  - slather coverage -x --scheme sdk-core-swift --workspace sdk-core-swift.xcworkspace sdk-core-swift.xcodeproj
  - ./cc-test-reporter after-build
  - codacy-analysis-cli analyze