osx_image: xcode10.1
language: swift
xcode_project: sdk-core-swift.xcworkspace 
xcode_scheme: sdk-core-swift
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

before_install:
  - gem install cocoapods --pr
  - pod repo update
  - gem install slather

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod 777 ./cc-test-reporter 

script:
  - ./cc-test-reporter before-build
  - pod install &&
    xcodebuild -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPhone\ X build test | xcpretty &&
    slather coverage -x --scheme sdk-core-swift --workspace sdk-core-swift.xcworkspace sdk-core-swift.xcodeproj

after_script:
  - ./cc-test-reporter after-build
