name: Build

on: 
  push: 


jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: true 
      matrix:
        destination: ['platform=iOS Simulator,OS=latest,name=iPhone11']

    steps:
    - uses: actions/checkout@v2
    - name: set up pod and xcpretty
      run: |
        gem install cocoapods --pr
        pod repo update
        gem install xcpretty
    - name: clear and prep
      run: | 
          pod deintegrate
    - name: build
      env: 
        destination: ${{ matrix.destination }}
      run: | 
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-3
        pod install
        xcodebuild clean test -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination "${destination}" -UseModernBuildSystem=NO | xcpretty
