name: Core Test

on: 
  pull_request: 


jobs:
  build:
    runs-on: macos-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,id:C3994F68-575B-4863-B4CE-19F7AA8BA89A,iOS=13.2.2,name=iPhone11']

    steps:
    - uses: actions/checkout@v2
    - name: clear and prep
      run: | 
          pod deintegrate
    - name: Build
      env: 
        destination: ${{ matrix.destination }}
      run: |
        xcrun simctl create iPhone11 com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-2
        pod install
        xcodebuild clean test -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination "${destination}" -UseModernBuildSystem=NO | xcpretty
