name: Swift

on: 
  push: 


jobs:
  build:
    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform:iOS Simulator, id:8A3E9176-C648-465E-891F-D3D15B0BF4C7, OS:13.1, name:iPhone 11']

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        pod deintegrate
        pod install
        xcodebuild clean test -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination platform="${destination}" CODE_SIGN_IDENTITY="" -UseModernBuildSystem=NO | xcpretty
      env: 
        destination: ${{ matrix.destination }}