name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run:  xcodebuild -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift
    - name: Run tests
      run: swift test -v
