name: Swift

on: 
  push: 


jobs:
  build:
    runs-on: macOS-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,iOS=13.1,name=iPhone 8']

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: | 
        pod deintegrate
        pod install
        xcodebuild clean test -workspace sdk-core-swift.xcworkspace -scheme sdk-core-swift -destination "${destination}" -UseModernBuildSystem=NO | xcpretty
      env: 
        destination: ${{ matrix.destination }}